import { Quote } from "./shared/UI";

export default function DailyDevotional() {
  // 31 unique devotionals — one for each day of the month, cycling monthly
  const devotionals = [
    { verse: "Whatever you ask in prayer, believe that you have received it, and it will be yours.", ref: "Mark 11:24", devotion: "This is the master instruction. Not \"believe that you might receive\" — believe that you HAVE received. Past tense. Goddard and Dispenza both point here: the feeling of the wish fulfilled is prayer in its highest form." },
    { verse: "Be still, and know that I am God.", ref: "Psalm 46:10", devotion: "Stillness isn't inactivity — it's the posture of reception. Before you broadcast any signal into the field, quiet yourself enough to receive. The coherent signal starts in silence." },
    { verse: "As a man thinks in his heart, so is he.", ref: "Proverbs 23:7", devotion: "Scripture said it thousands of years before Dispenza or Clear. Your inner state — what you think AND feel simultaneously — is literally who you are. Change the inner state first. The outer follows." },
    { verse: "I can do all things through Christ who strengthens me.", ref: "Philippians 4:13", devotion: "Not through your own willpower. Not through affirmations alone. Through Christ. The system works because the Source is infinite. Your job is coherence. His job is everything else." },
    { verse: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.", ref: "Romans 12:2", devotion: "Zeland calls them pendulums. Paul calls it \"the pattern of this world.\" Same warning: the collective will pull you into its frequency if you let it. Renew your mind daily — that's what this whole system is for." },
    { verse: "The kingdom of God is within you.", ref: "Luke 17:21", devotion: "Not above you, not ahead of you, not in some distant future — within you. The coherent field, the imagination, the faith that moves mountains. It's all already inside. Your practice is simply removing the blocks." },
    { verse: "Faith is the substance of things hoped for, the evidence of things not seen.", ref: "Hebrews 11:1", devotion: "Faith isn't wishful thinking — it has substance. It IS the evidence. When your thought and emotion cohere around something unseen, you're not pretending. You're operating at a higher level of reality than your five senses." },
    { verse: "Therefore I tell you, do not worry about your life. Look at the birds of the air; they do not sow or reap, yet your heavenly Father feeds them.", ref: "Matthew 6:25-26", devotion: "Worry is incoherence. It's electrical thought pointed at what you want plus magnetic emotion soaked in fear. Jesus says drop the fear entirely. Trust is the ultimate state of reduced importance." },
    { verse: "Delight yourself in the Lord, and he will give you the desires of your heart.", ref: "Psalm 37:4", devotion: "The sequence matters. Delight first — not as a strategy to get things, but as the state itself. When you delight in God, your desires align with His. Then they're not requests anymore. They're co-creations." },
    { verse: "God calls into being things that were not.", ref: "Romans 4:17", devotion: "This is the biblical basis for everything Goddard taught. Speaking and feeling things into existence isn't New Age — it's the oldest creative act. God spoke, and it was. You are made in that image." },
    { verse: "Commit your works to the Lord, and your plans will be established.", ref: "Proverbs 16:3", devotion: "Adams says build systems. Clear says build identity. Jesus says commit it all to the Lord. These aren't contradictions — they're layers. Build the system, embody the identity, then surrender the outcome. Your plans establish themselves." },
    { verse: "The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full.", ref: "John 10:10", devotion: "Life to the FULL. Not life barely survived. Not life endured. Christ's explicit promise is abundance — in joy, in purpose, in impact. If your faith feels like deprivation, something is misaligned." },
    { verse: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", ref: "Romans 8:28", devotion: "Even the setbacks. Even the days you miss every practice. Even the confusion. All of it is being worked for your good. This is the deepest form of reduced importance — trusting that the detours are part of the route." },
    { verse: "Create in me a pure heart, O God, and renew a steadfast spirit within me.", ref: "Psalm 51:10", devotion: "Coherence requires a clean signal. Unforgiveness, bitterness, hidden resentment — these create static. David knew: you have to ask for the clean heart before the signal clears. Today, let something go." },
    { verse: "I am the vine; you are the branches. Apart from me you can do nothing.", ref: "John 15:5", devotion: "The guard rail for the whole system. Every technique, every habit stack, every affirmation — it works because you're connected to the Vine. Disconnect, and it all becomes noise. Stay connected, and fruit is inevitable." },
    { verse: "The Lord is my shepherd, I lack nothing.", ref: "Psalm 23:1", devotion: "Read that again slowly. I lack NOTHING. This isn't future tense. It's the state Goddard would call \"the wish fulfilled.\" When you truly feel that you lack nothing, you've entered the frequency where abundance lives." },
    { verse: "But seek first his kingdom and his righteousness, and all these things will be given to you as well.", ref: "Matthew 6:33", devotion: "The priority stack is clear: Kingdom first, everything else second. Not because God is withholding — because when the priority is right, the signal is coherent, and everything else organizes around it naturally." },
    { verse: "For where your treasure is, there your heart will be also.", ref: "Matthew 6:21", devotion: "What you invest attention in becomes your magnetic center. Your heart follows your treasure — not the other way around. So be intentional about where you place your attention today. That's where your life is heading." },
    { verse: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", ref: "Joshua 1:9", devotion: "Courage isn't the absence of fear — it's coherence in the presence of it. When you feel the pull to shrink back from your calling, remember: the One who called you is with you. Step forward anyway." },
    { verse: "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.", ref: "Galatians 6:9", devotion: "Clear's 1% compound rule is a spiritual law. The harvest is coming, but it has a \"proper time.\" Your job isn't to force the timeline — it's to not give up. Faithfulness is the cheat code." },
    { verse: "Trust in the Lord with all your heart and lean not on your own understanding.", ref: "Proverbs 3:5", devotion: "Your rational mind will never fully understand how thought and emotion create reality. That's okay. Trust doesn't require understanding. It requires surrender — which is exactly the state where coherence is highest." },
    { verse: "Come to me, all you who are weary and burdened, and I will give you rest.", ref: "Matthew 11:28", devotion: "If your system is feeling heavy — if the affirmations feel forced, if the habits feel like chains — stop. Come to rest. Pillar 7 exists for a reason. The deepest coherence isn't effort. It's trust." },
    { verse: "If anyone is in Christ, the new creation has come: The old has gone, the new is here!", ref: "2 Corinthians 5:17", devotion: "Identity shift — the core of Clear's framework — is a biblical promise. In Christ, you are already the new creation. You're not becoming someone new. You're living into who you already are." },
    { verse: "Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.", ref: "Ephesians 3:20", devotion: "Immeasurably more than you can IMAGINE. Your boldest Goddard visualization, your most audacious affirmation — God says He can exceed it. Don't shrink your imagination. Expand it, then let God outdo it." },
    { verse: "I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.", ref: "John 16:33", devotion: "Jesus doesn't promise no resistance. He promises He's already overcome it. Zeland would call this the ultimate lifeline — walking a path where the outcome is already secured, even when the terrain is rough." },
    { verse: "The light shines in the darkness, and the darkness has not overcome it.", ref: "John 1:5", devotion: "Your coherent signal — thought + emotion + faith — is light. And no amount of darkness can extinguish it. On the hard days, remember: you don't have to fight the darkness. You just have to keep shining." },
    { verse: "Give, and it will be given to you. A good measure, pressed down, shaken together and running over.", ref: "Luke 6:38", devotion: "The generosity loop isn't metaphor — it's mechanics. Giving reduces importance around scarcity, affirms abundance as your current state, and opens channels you didn't know existed. Give first today." },
    { verse: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", ref: "Philippians 1:6", devotion: "You didn't start this journey. God did. And He finishes what He starts. On the days you feel like you're failing at the system, remember: the system isn't carrying you. He is." },
    { verse: "Blessed is the one who perseveres under trial because, having stood the test, that person will receive the crown of life.", ref: "James 1:12", devotion: "The crown doesn't go to the one who never struggled. It goes to the one who persevered. Every day you show up — even imperfectly — you're standing the test. Keep going." },
    { verse: "You did not choose me, but I chose you and appointed you so that you might go and bear fruit — fruit that will last.", ref: "John 15:16", devotion: "You were chosen before you built any system. Before the first affirmation, before the first meditation. He chose you. Your practices don't earn His love — they align you with a calling He already placed on your life." },
    { verse: "And my God will meet all your needs according to the riches of his glory in Christ Jesus.", ref: "Philippians 4:19", devotion: "ALL your needs. According to HIS riches — which are infinite. Not according to your effort, your streak count, or your coherence score. According to His glory. Rest in that today." },
  ];

  const dayOfMonth = new Date().getDate();
  const d = devotionals[(dayOfMonth - 1) % devotionals.length];

  return (
    <div style={{ marginTop: "2rem", background: "rgba(200,169,81,0.03)", border: "1px solid rgba(200,169,81,0.1)", borderRadius: 3, overflow: "hidden" }}>
      <div style={{ padding: "0.6rem 1rem", borderBottom: "1px solid rgba(200,169,81,0.08)", display: "flex", alignItems: "center", gap: "0.5rem" }}>
        <span style={{ fontSize: "0.85rem" }}>📜</span>
        <span style={{ fontSize: "0.62rem", letterSpacing: "0.15em", textTransform: "uppercase", color: "#C8A951", opacity: 0.7 }}>Today's Devotional</span>
      </div>
      <div style={{ padding: "1.2rem 1.2rem" }}>
        <div style={{ borderLeft: "2px solid rgba(200,169,81,0.4)", padding: "0 0 0 1.2rem", marginBottom: "1rem" }}>
          <div style={{ fontFamily: "'Georgia',serif", fontSize: "1.05rem", fontWeight: 300, fontStyle: "italic", lineHeight: 1.55, color: "#D4CFC4" }}>"{d.verse}"</div>
          <div style={{ fontSize: "0.62rem", letterSpacing: "0.12em", textTransform: "uppercase", color: "#8A8678", marginTop: "0.5rem" }}>— {d.ref}</div>
        </div>
        <div style={{ fontSize: "0.82rem", color: "#8A8678", lineHeight: 1.7 }}>{d.devotion}</div>
      </div>
    </div>
  );
}
